---
abstract: 'What BigInts are before they become big'
author:
  - '(C) by Tels L<http://bloodgate.com/> 2002-2007. '
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.52
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BigInt-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigInt: 1.9
  Math::BigRat: 0.19
  perl: 5.006002
resources:
  license: http://dev.perl.org/licenses/
version: 0.13
