--- 
abstract: What BigInts are before they become big
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.52
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Math-BigInt-Lite
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Math::BigInt: 1.86
  Math::BigRat: 0.19
  perl: 5.6.2
version: 0.12
